# Generated by Django 6.0.5 on 2026-05-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblMedicineCategory',
            fields=[
                ('MedicineCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineCategoryName', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblMedicine',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
                ('ManufacturingDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('Unit', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('MedicineCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.tblmedicinecategory')),
            ],
        ),
        migrations.CreateModel(
            name='TblMedicineStock',
            fields=[
                ('MedicineStockId', models.AutoField(primary_key=True, serialize=False)),
                ('StockInHand', models.IntegerField()),
                ('ReOrderLevel', models.IntegerField()),
                ('Purchase', models.IntegerField()),
                ('Issuance', models.IntegerField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('MedicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.tblmedicine')),
            ],
        ),
    ]
