# Generated by Django 6.0.5 on 2026-05-14 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMembership',
            fields=[
                ('MembershipId', models.AutoField(primary_key=True, serialize=False)),
                ('MembershipType', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblPatient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('MembershipId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionist.tblmembership')),
            ],
        ),
        migrations.CreateModel(
            name='TblAppointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateField()),
                ('TokenNumber', models.IntegerField()),
                ('ConsultationStatus', models.CharField(default='Scheduled', max_length=20)),
                ('IsActive', models.BooleanField(default=True)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbldoctor')),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblpatient')),
            ],
        ),
    ]
