# Generated by Django 6.0.5 on 2026-05-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBilling',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RegistrationCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('AdditionalCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BillDate', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblappointment')),
            ],
        ),
    ]
