# Generated by Django 6.0.5 on 2026-05-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblLabTestCategory',
            fields=[
                ('LabTestCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('LabTestCategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblLabTest',
            fields=[
                ('LabTestId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReferenceMinRange', models.CharField(max_length=50)),
                ('ReferenceMaxRange', models.CharField(max_length=50)),
                ('SampleRequired', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('LabTestCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_technician.tbllabtestcategory')),
            ],
        ),
    ]
