# Generated by Django 6.0.5 on 2026-05-14 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=20, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tblrole')),
            ],
        ),
    ]
