# Generated by Django 6.0.5 on 2026-05-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblSpecialization',
            fields=[
                ('SpecializationId', models.AutoField(primary_key=True, serialize=False)),
                ('SpecializationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblStaff',
            fields=[
                ('StaffId', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('JoiningDate', models.DateField(auto_now_add=True)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('UserName', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('IsActive', models.BooleanField(default=True)),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tblrole')),
            ],
        ),
        migrations.CreateModel(
            name='TblDoctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('SpecializationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tblspecialization')),
                ('StaffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tblstaff')),
            ],
        ),
    ]
